api:
  name: "is-flights-sa"
  basepath: "is-flights-sa/api/${api.version}"
  version: "v1"

db:
  host: "mudb.mule-training.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
  
mongodb:
  connection_string: "mongodb+srv://svc_flights_dev:mulepass@dev-cluster-01.cnxz8nx.mongodb.net/flights_api_db?appName=dev-cluster-01"